nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_credentials: false  # Changez à false pour éviter les conflits
            max_age: 3600
        '^/auth/':
            allow_origin: ['http://localhost:5173', 'http://127.0.0.1:5173']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_credentials: false  # Changez à false
            max_age: 3600


# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['http://localhost:5173']
#         allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/api/':
#             allow_origin: ['http://localhost:5173']
#             allow_headers: ['*']
#             allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#             allow_credentials: true
#             max_age: 3600
#         '^/auth/':
#             allow_origin: ['http://localhost:5173']
#             allow_headers: ['*']
#             allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#             allow_credentials: true
#             max_age: 3600